services:
  - type: web
    name: mazunte-whatsapp-listener
    env: node
    region: oregon
    plan: starter
    buildCommand: yarn install
    startCommand: yarn start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: WHATSAPP_GROUPS
        sync: false
      - key: SUPABASE_STORAGE_BUCKET
        value: whatsapp-media
      - key: RUN_MIGRATIONS
        value: true
